name: quill_ai
description: Quill AI App.
Developed by: "Abdul Samad"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  loggy: ^2.0.3
  go_router: ^14.2.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^8.0.5
  image_picker: ^1.0.7
  syncfusion_flutter_pdf: ^26.1.40
  syncfusion_flutter_pdfviewer: ^26.1.40
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0
  speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2

  # iOS
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/

dependency_overrides:
  web: 0.3.0
